// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsqiylycebkxliggotxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcWl5bHljZWJreGxpZ2dvdHh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjgxMDAsImV4cCI6MjA2NzkwNDEwMH0.MXWn2G8U4Xmt-50M_Uyn1kFC57gJpr2TpEJMyIKtO-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});